source 'http://rubygems.org'
gem 'sinatra'
gem 'data_mapper'
gem 'pg'
gem 'dm-postgres-adapter'
gem 'puma'
gem 'roar', '0.12.9'
gem 'mustache', '~> 0.99.6'
gem 'rerun'
gem 'pry'
gem 'pry-remote'
gem 'pry-doc'